# -*- coding: utf-8 -*-
"""Gallstone_Research_Production_Narrative.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14toSeBbrBvOL_bMpDKuNF7thLRQM99-c

# Gallstone Research: Production Narrative

**Murine Cholelithiasis — Bridge Between Modular Software Engineering and Academic Research Rigor**

This notebook is powered by the project's modular Python scripts: `data_loader.py`, `preprocess.py`, `model_trainer.py`, and `error_analysis.py`. All computations and visualizations below are produced by calling these modules to ensure production reproducibility and alignment with the deployed pipeline. It includes a **correlation heatmap** of engineered and key features vs. the target (Section 6.1) and a **Prediction Case Study** (Section 13) for live single-animal inference using `predict_sample.py`.
"""

# Commented out IPython magic to ensure Python compatibility.
# Modular imports: production pipeline (data_loader, preprocess, model_trainer, error_analysis)
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore", message="FigureCanvasAgg is non-interactive", category=UserWarning)

# %matplotlib inline

from data_loader import build_master_dataframe
from preprocess import prepare_training_dataframe
from model_trainer import build_pipelines, evaluate_models, select_best_model, fit_best_pipeline, RANDOM_STATE, CHAMPION_MODEL
from error_analysis import run_error_analysis

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import Image, display

"""---
## 1. Project Abstract

Murine models of cholelithiasis provide a controlled setting to identify dietary and metabolic determinants of gallstone formation. This project applies a machine learning pipeline to a multi-source phenotypic dataset comprising 385 obesity-prone mice to predict binary gallstone presence ($st\_pres$) from morphometric, lipid, and strain-level summary variables. Individual phenotypes were synthesised with population-level strain summaries; after row-wise filtering to retain only verified outcomes (291 animals), we engineered three derived features—$weight\_gain\_pct$, $cholesterol\_ratio$, and $non\_hdl\_calc$—and excluded leakage variables and columns with more than 70% missingness. We compared a univariate baseline, Calibrated Logistic Regression, Random Forest, and XGBoost under stratified 5-fold cross-validation; **metrics are reported as mean ± SD across folds**. The **champion model is Calibrated Logistic Regression** (recall 0.771 ± 0.04), chosen for high recall, interpretability, and isotonic-calibrated probabilities. SHAP analysis revealed that total cholesterol and $weight\_gain\_pct$ are among the principal drivers of predicted risk. A central finding was the **Weight Gain Paradox**: $weight\_gain\_pct$ emerged as a top-three predictor despite its negative marginal correlation with the outcome, reflecting non-linear metabolic phenotypes and strain-specific biliary responses. Strain-level error analysis (using CV-based predictions) identifies strains where the model fails (e.g. elevated false negative rate). These results support calibrated probabilistic models and engineered metabolic trajectory features for risk stratification in lithogenic diet studies.

---
## 2. Hardware & Environment

**Compute platform:** Training and SHAP explanation generation are designed to run on an **NVIDIA RTX 5070** GPU to highlight local high-performance compute capabilities. The pipeline uses CPU for scikit-learn and SHAP (LinearExplainer); XGBoost can optionally use GPU when built with CUDA support (e.g. `tree_method='gpu_hist'` when `USE_GPU=1`).

**Software stack:**
- **Python** 3.8+ with standard scientific stack (NumPy, Pandas)
- **Scikit-Learn** — Logistic Regression, Random Forest, CalibratedClassifierCV, StratifiedKFold, SimpleImputer, ColumnTransformer, preprocessing
- **XGBoost** — gradient boosting classifier (class-weighted, CPU or GPU)
- **SHAP** — LinearExplainer for Logistic Regression interpretability
- **Matplotlib / Seaborn** — visualizations and calibration plots
- **Joblib** — model serialisation (best_gallstone_model.pkl, deployed_gallstone_model.pkl)

**Reproducibility:** Fixed random seeds (e.g. `RANDOM_STATE=42`) in model_trainer ensure reproducible train/validation splits and model fits across runs.

---
## 3. Modular Architecture Overview

We chose a **script-based modular workflow** over a single monolithic notebook for production reproducibility and maintainability. The pipeline is split into focused modules:

- **data_loader.py** — Loads and merges the three CSVs; single source of truth for join logic and column alignment.
- **preprocess.py** — Row filtering (verified $st\_pres$ only), type coercion, feature engineering, anti-leakage exclusion, and imputation. Returns the same $X$ and $y$ used in training and deployment.
- **model_trainer.py** — Builds pipelines (univariate baseline, LR, RF, XGB), runs stratified 5-fold CV, uses **Calibrated Logistic Regression** as the fixed champion (for paper/SHAP consistency), generates calibration and PR plots, and saves the best and deployed models.
- **error_analysis.py** — Loads the saved model and training data, computes per-strain misclassification counts, and outputs the top-5 strains table (e.g. for biological outlier identification).

This design ensures that the same code paths power both this narrative notebook and headless batch runs (e.g. CI or scheduled retraining). The notebook imports and calls these modules rather than reimplementing logic, so any change in preprocessing or model choice is reflected everywhere.

---
## 4. Data Integration Strategy

Per-animal phenotype data (**Paigen3.csv**) and aligned metadata (**Paigen3_animaldata.csv**) are joined on a composite key: **Strain**, **Sex**, **Age**, and **Animal ID** (with animal ID normalised from the second file by taking the substring before the first colon). Strain-level longitudinal summary data (**Paigen3_strainmeans.csv**) is in long form (one row per strain × sex × variable). It is pivoted to wide format (one column per variable mean, prefixed e.g. `strainmean_totalCh`) and merged onto the per-animal data on **Strain** and **Sex**, so each animal receives its strain–sex contextual features without using its own outcome. The result is a single master dataframe used for all downstream steps.
"""

# Use data_loader to build the integrated master dataframe
master_df, df_paigen, df_animal, df_strainmeans = build_master_dataframe()
print("Master dataframe shape:", master_df.shape)
print("Columns (sample):", list(master_df.columns[:12]) + ["..."])
master_df.head(3)

"""---
## 5. Data Surgery & Cleaning

Rows with missing target $st\_pres$ are removed so that training and evaluation use only **verified** outcomes. The result is **291 valid samples** and **94 records with missing labels** excluded. The class distribution in the analysis set is **62 Stone (positive)** and **229 No Stone (negative)**. Below we visualise this split and the class imbalance to justify class-weighted fitting and recall-focused model selection.
"""

df_filtered, X_imputed, y, _ = prepare_training_dataframe()
y = y.astype(int)

# Counts: valid vs missing (from original 385)
n_valid = len(y)
n_missing = 385 - n_valid
n_stone = (y == 1).sum()
n_no_stone = (y == 0).sum()

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

axes[0].bar(["Valid (used)", "Missing (excluded)"], [n_valid, n_missing], color=["steelblue", "lightgray"])
axes[0].set_ylabel("Number of animals")
axes[0].set_title("Sample inclusion: 291 valid vs 94 missing st_pres")

axes[1].bar(["No Stone (0)", "Stone (1)"], [n_no_stone, n_stone], color=["steelblue", "coral"])
axes[1].set_ylabel("Count")
axes[1].set_title("Class balance: 229 vs 62")
plt.tight_layout()
plt.show()

print(f"Valid samples: {n_valid} | Excluded (missing st_pres): {n_missing}")
print(f"No Stone: {n_no_stone} | Stone: {n_stone}")

"""---
## 6. Feature Engineering

Three derived metrics are computed and used in all models.

**Weight gain percentage** (relative change in body weight over the study):

$$weight\_gain\_pct = \frac{finalbw - initbw}{initbw} \times 100$$

**Cholesterol ratio** (total to HDL cholesterol):

$$cholesterol\_ratio = \frac{totalCh}{HDL\_Ch}$$

**Calculated non-HDL cholesterol** (validated against existing $nonHDL\_Ch$):

$$non\_hdl\_calc = totalCh - HDL\_Ch$$
"""

# Confirm engineered columns exist in the preprocessed feature matrix
engineered = ["weight_gain_pct", "cholesterol_ratio", "non_hdl_calc"]
present = [c for c in engineered if c in X_imputed.columns]
print("Engineered features in X_imputed:", present)
X_imputed[present].describe().round(3)

"""---
## 7. Anti-Leakage Protocol

To preserve **model integrity** and prevent target leakage, the following are **excluded** from the feature set:

- **$gs$** (gallstone score) and **$nstones$** (number of stones) — direct proxies for the outcome $st\_pres$.
- **$st\_pres$** — the target itself.
- **$animal\_short\_id$**, **$animal\_id$**, **$comments$** — identifiers and free text not suitable as predictors.

Additionally, any column with **more than 70% missing values** is dropped (e.g. many histology and metabolic columns) to avoid destabilising the model. This anti-leakage protocol is implemented in `preprocess.py` and is shared by training, evaluation, and deployment.
"""

# Correlation heatmap: engineered features and key variables with target st_pres
engineered = ["weight_gain_pct", "cholesterol_ratio", "non_hdl_calc"]
key_vars = [c for c in ["totalCh", "HDL_Ch", "initbw", "finalbw", "bw_chg"] if c in X_imputed.columns]
cols = [c for c in engineered + key_vars if c in X_imputed.columns]
corr_df = X_imputed[cols].copy()
corr_df["st_pres"] = y.values
corr_mat = corr_df.corr()

plt.figure(figsize=(8, 6))
sns.heatmap(corr_mat, annot=True, fmt=".2f", cmap="RdBu_r", center=0, square=True)
plt.title("Correlation Heatmap: Engineered and Key Features vs st_pres")
plt.tight_layout()
plt.show()

"""---
## 8. The Baseline Competition

A **univariate statistical baseline** (logistic regression on $weight\_gain\_pct$, $totalCh$, $cholesterol\_ratio$ only) is compared with three full-pipeline classifiers. All models are evaluated under **stratified 5-fold cross-validation**; the **mean and standard deviation** across the five folds are reported so that variance with respect to the data split is visible. The **champion model is fixed to Calibrated Logistic Regression** for paper, SHAP (LinearExplainer), and deployment consistency; it is chosen for high recall (0.771 ± 0.04), interpretability, and clinically usable (isotonic-calibrated) probabilities.

| Model | Precision (mean ± SD) | Recall (mean ± SD) | F1 (mean ± SD) |
|-------|------------------------|---------------------|-----------------|
| Univariate baseline | 0.29 ± 0.08 | 0.61 ± 0.16 | 0.40 ± 0.10 |
| **Calibrated Logistic Regression** | **0.615 ± 0.04** | **0.771 ± 0.04** | **0.682 ± 0.04** |
| Random Forest | 0.749 ± 0.10 | 0.497 ± 0.12 | 0.589 ± 0.10 |
| XGBoost | 0.736 ± 0.07 | 0.597 ± 0.08 | 0.654 ± 0.04 |
"""

pipelines, num_cols, cat_cols = build_pipelines(X_imputed, y)
metrics = evaluate_models(pipelines, X_imputed, y)
# Champion fixed to Calibrated LR for paper/SHAP/deployment consistency (see CHAMPION_MODEL in model_trainer)
best_name = CHAMPION_MODEL

# Build display table: mean ± std for precision, recall, f1 (include univariate baseline)
model_order = ["univariate_baseline", "log_reg", "rf", "xgb"]
labels = ["Univariate baseline", "Calibrated Logistic Regression", "Random Forest", "XGBoost"]
rows = []
for name, label in zip(model_order, labels):
    if name not in metrics:
        continue
    m = metrics[name]
    row = {
        "Precision": f"{m['precision']:.3f} ± {m['precision_std']:.3f}",
        "Recall": f"{m['recall']:.3f} ± {m['recall_std']:.3f}",
        "F1": f"{m['f1']:.3f} ± {m['f1_std']:.3f}",
    }
    rows.append(row)
metrics_df = pd.DataFrame(rows, index=[labels[i] for i, n in enumerate(model_order) if n in metrics])
print("Stratified 5-fold CV results (mean ± SD across 5 folds; champion = Calibrated LR)")
display(metrics_df)
print(f"Champion model (for export and figures): {best_name}")

"""---
## 9. Clinical Calibration Strategy

Raw Logistic Regression outputs are often **poorly calibrated**: predicted probabilities do not match observed event rates. We apply **Isotonic Calibration** (CalibratedClassifierCV with method `isotonic`, 5-fold) to the full pipeline. To **quantify** calibration, the pipeline reports **Brier score** and **Expected Calibration Error (ECE)** for calibrated vs. uncalibrated LR; values are saved in `results_plots/cv_metrics.json`. The calibration plot (reliability diagram) below compares mean predicted probability per bin to the fraction of positives; the deployed model is saved as `deployed_gallstone_model.pkl` for use in production inference.
"""

calibrated_lr = pipelines["log_reg"]
calibrated_lr.fit(X_imputed, y)

from sklearn.calibration import calibration_curve
y_proba = calibrated_lr.predict_proba(X_imputed)[:, 1]
frac_pos, mean_pred = calibration_curve(y, y_proba, n_bins=10)

plt.figure(figsize=(6, 4))
plt.plot(mean_pred, frac_pos, "s-", label="Calibrated model")
plt.plot([0, 1], [0, 1], "k--", label="Perfectly calibrated")
plt.xlabel("Mean predicted probability")
plt.ylabel("Fraction of positives")
plt.title("Isotonic calibration: reliability diagram")
plt.legend(loc="lower right")
plt.tight_layout()
plt.show()

"""---
## 10. Explainability (SHAP Analysis) and the Weight Gain Paradox

SHAP (SHapley Additive exPlanations) is used to explain the Logistic Regression model's predictions. The summary plot ranks features by their average impact on the model output and shows whether high or low values push the prediction toward **Stone** (positive SHAP) or **No Stone** (negative SHAP).

A central finding is the **Weight Gain Paradox**: $weight\_gain\_pct$ ranks **#3** in Random Forest feature importance (behind histology-derived $sandysto$ and $ChMC$), despite exhibiting a **negative** linear correlation with $st\_pres$ in the raw data. Tree-based models capture **interactions** between weight trajectory and other factors (strain, sex, diet, lipid profile); thus $weight\_gain\_pct$ can be a strong **conditional** predictor even when its marginal correlation is weak or negative. This suggests that bile composition and strain-specific metabolic responses play a more complex role than weight gain alone.
"""

# Embed the SHAP summary plot produced by the pipeline (final_report_generator or model_trainer)
import os
shap_path = os.path.join("results_plots", "shap_summary.png")
if os.path.isfile(shap_path):
    display(Image(filename=shap_path, width=800))
else:
    print("Run final_report_generator.py or model_trainer.py to generate results_plots/shap_summary.png")

"""---
## 11. Production Error Analysis

Strain-level error analysis **exposes where the model fails**. We use **out-of-sample predictions** from stratified 5-fold CV (each animal's prediction from a fold where it was held out) so that errors reflect real generalisation, not in-sample overfit. We report (1) **top strains by number of misclassifications** (where mistakes concentrate) and (2) **top strains by error rate** (min 5 samples, at least one mistake) with **false negative rate among Stone-positive** animals. Tables are saved as `results_plots/top5_strain_by_mistakes.csv` and `top5_strain_by_error_rate.csv`.
"""

# run_error_analysis returns (by_mistakes, by_error_rate); uses CV predictions by default
by_mistakes, by_error_rate = run_error_analysis(top_n=5)
print("Top 5 strains by number of misclassifications (where mistakes concentrate)")
display(by_mistakes)
print("\nTop 5 strains by error rate (min n=5, where the model fails most severely)")
display(by_error_rate)
if len(by_error_rate) > 0 and by_error_rate["n_mistakes"].iloc[0] > 0:
    worst = by_error_rate.iloc[0]
    print(f"\nFinding: 0% error on some strains; error rate {worst['error_rate']:.1%} (FN rate among Stone = {worst['fn_rate_among_positive']:.1%}) on strain: {worst['strain']}")

"""---
## 12. Future Work & Conclusion

**Summary of findings:** This project demonstrated a machine learning pipeline for predicting gallstone presence in obesity-prone mice using integrated phenotypic and strain-level data. Performance is reported with **mean ± SD across 5-fold CV**; a **univariate baseline** (weight and cholesterol only) shows that the full pipeline adds value. The **champion model is Calibrated Logistic Regression** (recall 0.771 ± 0.04), retained for deployment, interpretability, and calibrated probability outputs. Engineered features—in particular $weight\_gain\_pct$ and $cholesterol\_ratio$—proved informative, with $weight\_gain\_pct$ emerging as a top predictor in the Random Forest despite a negative marginal correlation with the outcome (Weight Gain Paradox). SHAP analysis and strain-level error analysis support the biological interpretability of the model and the identification of strains that may require further validation.

**Future work:** The pipeline is designed to scale to larger metabolic datasets. Potential extensions include: (1) incorporating longitudinal or multi-timepoint features for prognostic modelling; (2) Bayesian or post-hoc calibration refinements; (3) integration of genetic or transcriptomic covariates; (4) joint modelling of gallstone risk with other metabolic endpoints for multi-disease stratification. The modular script-based architecture (data_loader, preprocess, model_trainer, error_analysis) provides a reproducible, production-ready foundation for such extensions.

---
## 13. Prediction Case Study (Live Inference)

Using the same logic as **predict_sample.py**, we input one mouse's data and output its **calibrated probability** of gallstone formation. Missing features are filled from the training-set template. This demonstrates production-ready single-animal inference with the deployed model.
"""

# Reuse predict_sample logic: one mouse as dict -> calibrated P(Stone)
from predict_sample import predict_probability

# Example: one mouse with weights and lipids (missing features filled from training template)
mouse_case = {
    "strain": "B6.Cg-A<y>/J",
    "sex": "f",
    "age": 58.0,
    "initbw": 24.6,
    "finalbw": 23.5,
    "totalCh": 172.0,
    "HDL_Ch": 46.0,
    "liverweight": 1.75,
    "gbvol": 3.3,
}

# Use deployed (calibrated) model; fallback to best_gallstone_model.pkl if needed
try:
    prob = predict_probability(feature_dict=mouse_case)
except FileNotFoundError:
    prob = predict_probability(model_path="best_gallstone_model.pkl", feature_dict=mouse_case)

print("Prediction Case Study: Single-mouse input")
print("Input (subset):", mouse_case)
print(f"\nCalibrated P(Stone) = {prob:.4f}")